name: Image Consumer

on:
  schedule:
    - cron: '30 */12 * * *'  # Run 30 minutes after producer
  workflow_dispatch:

jobs:
  consume-images:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Install Dependencies
        run: pnpm install

      - name: Run Consumer
        run: pnpm run consume
        
      - name: Handle Failure
        if: failure()
        run: |
          echo "Consumer job failed at $(date)"
          exit 1 